# Generated by Django 4.2.8 on 2023-12-07 14:20

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCareWorker',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('preferred_name', models.CharField(blank=True, max_length=255)),
                ('pronouns', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('specialization', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
