# Generated by Django 4.2.8 on 2023-12-08 03:14

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_add_health_care_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('info', models.TextField()),
                ('health_care_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.healthcareworker')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('health_care_worker', 'date'), name='unique_appointment_date_health_care_worker'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('date__gt', django.db.models.functions.datetime.Now())), name='appointment_date_must_be_in_the_future'),
        ),
    ]
